apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: capz-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: management
        url: https://kubernetes.default.svc
        workload-cluster: minion1
  template:
    metadata:
      name: '{{workload-cluster}}'
    spec:
      project: clusters
      source:
        repoURL: 'https://github.com/xinity/cds23-demo'
        targetRevision: 0.0.6
        chart: capi-aks
        helm:
          values: |
            controlAgentPoolNodeSize: Standard_B4ms
            workerAgentPoolNodeSize: Standard_B4ms
            sshPublicKey: ""
            location: southcentralus
            name: '{{workload-cluster}}'
            clusterResourceGroupName: '{{workload-cluster}}'
            subscriptionId: f22d63d0-6093-4a8f-83f3-7598e8fb6eb3
      destination:
        server: '{{url}}'
        namespace: '{{workload-cluster}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
