apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: capz-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: management
        url: https://kubernetes.default.svc
        workload-cluster: cds23capz1
  template:
    metadata:
      name: '{{workload-cluster}}'
    spec:
      project: clusters
      source:
        repoURL: 'https://joaquinrz.github.io/capi-gitops'
        targetRevision: 0.0.6
        chart: capi-aks
        helm:
          values: |
	    controlAgentPoolNodes: 1
	    workerAgentPoolNodes: 1
            k8sVersion: v1.26.6
            controlAgentPoolNodeSize: Standard_B4ms
            workerAgentPoolNodeSize: Standard_B4ms
            sshPublicKey: ""
            location: westeurope
            name: '{{workload-cluster}}'
            clusterResourceGroupName: '{{workload-cluster}}'
            subscriptionId: b8ae8e74-628e-486e-9e9e-31be47234d4b
      destination:
        server: '{{url}}'
        namespace: '{{workload-cluster}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
