apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: imdb
    spec:
      containers:
        - name: app
          image: ghcr.io/kubernetes101/imdb-app:latest
          imagePullPolicy: Always

          args:
          - --in-memory
          - --zone
          - {{ .Values.zone }}
          - --region
          - {{ .Values.region }}

          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP

          readinessProbe:
            initialDelaySeconds: 5
            failureThreshold: 60
            periodSeconds: 2
            httpGet:
              path: /readyz
              port: {{ .Values.port }}

          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 60
            httpGet:
              path: /healthz
              port: {{ .Values.port }}

          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 64Mi

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.name }}
